FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get upgrade -y \
    && apt-get install -y csh \
    && apt-get install -y flex \
    && apt-get install -y  gfortran \
    && apt-get install -y g++ \
    && apt-get install -y xorg-dev \
    && apt-get install -y zlib1g-dev \
    && apt-get install -y  libbz2-dev \
    && apt-get install -y  patch \
    && apt-get install -y  python-tk \
    && apt-get install -y  python-matplotlib \
    && apt-get install -y mpich 
